/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIScreens_package;

import GUIScreensCode.Difficulty;
import GUIScreensCode.FrameUtils;
import GUIScreensCode.QuizType;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author SD10009935 - Alex von Allemann 12-5/K1 DifficultySelectionTimesTables
 */
public class DifficultySelectionTimesTables extends javax.swing.JFrame {

    private ProfileScreen profileScreen;
    private QuizSelectionScreen.AlgebraQuizListener Listener;

    /**
     * Creates new form DifficultySelectionTimesTables. Initializes components,
     * sets a green background, applies saved background color, and sets a tool
     * tip for user guidance.
     */
    public DifficultySelectionTimesTables() {
        initComponents();
        getContentPane().setBackground(Color.green); //Green background.
        Color col = new Color(0, 102, 0);
        getContentPane().setBackground(col); //Set background color to green.
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();
        ToolTip.setToolTipText("Higher difficulty means less time! Choose wisely for a challenging experience.");
    }

    /**
     * Applies the saved background color to the container.
     */
    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

    /**
     * Recursively changes the background color of all JPanel components within
     * the given container.
     *
     * @param container The container to search for JPanel components.
     * @param color The color to set for JPanel backgrounds.
     */
    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TImesTablesHeading = new javax.swing.JLabel();
        EasyDifficulty = new javax.swing.JButton();
        MediumDifficulty = new javax.swing.JButton();
        HardDifficulty = new javax.swing.JButton();
        Time8min = new javax.swing.JLabel();
        Time4min = new javax.swing.JLabel();
        Time1min30sec = new javax.swing.JLabel();
        TimesTableImage = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ToolTip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        TImesTablesHeading.setBackground(new java.awt.Color(255, 153, 51));
        TImesTablesHeading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TImesTablesHeading.setText("The Times Tables: (1 to 12)");

        EasyDifficulty.setBackground(new java.awt.Color(255, 102, 0));
        EasyDifficulty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EasyDifficulty.setText("Easy");
        EasyDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyDifficultyActionPerformed(evt);
            }
        });

        MediumDifficulty.setBackground(new java.awt.Color(255, 102, 0));
        MediumDifficulty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MediumDifficulty.setText("Medium");
        MediumDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumDifficultyActionPerformed(evt);
            }
        });

        HardDifficulty.setBackground(new java.awt.Color(255, 102, 0));
        HardDifficulty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HardDifficulty.setText("Hard");
        HardDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardDifficultyActionPerformed(evt);
            }
        });

        Time8min.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Time8min.setText("Time: 8 minutes");

        Time4min.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Time4min.setText("Time: 4 minutes");

        Time1min30sec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Time1min30sec.setText("Time: 1 minute 30 seconds");

        TimesTableImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/TimesTableImage.jpg"))); // NOI18N

        BackButton.setBackground(new java.awt.Color(255, 102, 0));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ToolTip.setToolTipText("Choose a quiz category to begin. Each category offers different challenges!\n");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimesTableImage, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EasyDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MediumDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HardDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Time1min30sec)
                                .addGap(87, 87, 87))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Time4min, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time8min, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(TImesTablesHeading)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TImesTablesHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimesTableImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EasyDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time8min, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MediumDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time4min, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HardDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Time1min30sec, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        QuizSelectionScreen QuizBackButton = new QuizSelectionScreen(profileScreen, Listener);
        QuizBackButton.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void EasyDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyDifficultyActionPerformed
        // TODO add your handling code here:
        Difficulty selectedDifficulty = Difficulty.EASY;
        QuizAnswerScreen QuizAnswer = new QuizAnswerScreen(selectedDifficulty, QuizType.TIMES_TABLES);
        QuizAnswer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EasyDifficultyActionPerformed

    private void MediumDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumDifficultyActionPerformed
        // TODO add your handling code here:
        Difficulty selectedDifficulty = Difficulty.MEDIUM;
        QuizAnswerScreen QuizAnswer = new QuizAnswerScreen(selectedDifficulty, QuizType.TIMES_TABLES);
        QuizAnswer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MediumDifficultyActionPerformed

    private void HardDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardDifficultyActionPerformed
        // TODO add your handling code here:
        Difficulty selectedDifficulty = Difficulty.HARD;
        QuizAnswerScreen QuizAnswer = new QuizAnswerScreen(selectedDifficulty, QuizType.TIMES_TABLES);
        QuizAnswer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HardDifficultyActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DifficultySelectionTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DifficultySelectionTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DifficultySelectionTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DifficultySelectionTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DifficultySelectionTimesTables().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EasyDifficulty;
    private javax.swing.JButton HardDifficulty;
    private javax.swing.JButton MediumDifficulty;
    private javax.swing.JLabel TImesTablesHeading;
    private javax.swing.JLabel Time1min30sec;
    private javax.swing.JLabel Time4min;
    private javax.swing.JLabel Time8min;
    private javax.swing.JLabel TimesTableImage;
    private javax.swing.JLabel ToolTip;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
