/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIScreens_package;

import GUIScreensCode.FrameUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Alex von Allemann 12-5/K1 HomeScreenGUI
 */
public class HomeScreen extends javax.swing.JFrame {
    
      private ProfileScreen profileScreen; // Instance variable for ProfileScreen
      private QuizSelectionScreen.AlgebraQuizListener Listener;

    ImageIcon imageHat = new ImageIcon("Hat.jpg");
    public HomeScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        //getContentPane() method
        //Returns the contentPane object for this frame.
       // getContentPane().setBackground(Color.green); //You can use Color class standard color names.

        //or you can use color object and assign red,green, blue color values
        // to create any color that I want.
        //Color col = new Color(0, 102, 0);
        //getContentPane().setBackground(col);
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();
    }
    
    /**
     * Applies the saved background color to the content pane.
     * Retrieves the saved color from FrameUtils and updates the background
     * of the entire container.
     */
    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

     /**
     * Recursively changes the background color of all JPanel components within a container.
     * Iterates through all components in the container. If a component is a JPanel,
     * sets its background color to the specified color. Recursively applies the color
     * to nested containers.
     * 
     * @param container The container whose components background colors to change
     * @param color The color to set as the background
     */
    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GreenBackground = new javax.swing.JPanel();
        HomePageHeading = new javax.swing.JLabel();
        QuizSelectionButton = new javax.swing.JButton();
        LeaderboardsButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        ProfileButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        AppIcon = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));

        GreenBackground.setBackground(new java.awt.Color(0, 102, 0));

        HomePageHeading.setBackground(new java.awt.Color(255, 102, 51));
        HomePageHeading.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        HomePageHeading.setText("Welcome to MathsPRO Quiz!");

        QuizSelectionButton.setBackground(new java.awt.Color(255, 102, 0));
        QuizSelectionButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QuizSelectionButton.setText("Select Quiz");
        QuizSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizSelectionButtonActionPerformed(evt);
            }
        });

        LeaderboardsButton.setBackground(new java.awt.Color(255, 102, 0));
        LeaderboardsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LeaderboardsButton.setText("Leaderboards");
        LeaderboardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaderboardsButtonActionPerformed(evt);
            }
        });

        HelpButton.setBackground(new java.awt.Color(255, 102, 0));
        HelpButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HelpButton.setText("Help!");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });

        ProfileButton.setBackground(new java.awt.Color(255, 102, 0));
        ProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProfileButton.setText("My Profile");
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        SettingsButton.setBackground(new java.awt.Color(255, 102, 0));
        SettingsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SettingsButton.setText("Settings");
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        AppIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AppLogo.png"))); // NOI18N

        javax.swing.GroupLayout GreenBackgroundLayout = new javax.swing.GroupLayout(GreenBackground);
        GreenBackground.setLayout(GreenBackgroundLayout);
        GreenBackgroundLayout.setHorizontalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(HomePageHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(QuizSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LeaderboardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AppIcon)))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GreenBackgroundLayout.setVerticalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HomePageHeading)
                    .addComponent(HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LeaderboardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AppIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GreenBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QuizSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizSelectionButtonActionPerformed
        // TODO add your handling code here:
        
         ProfileScreen profileScreenInstance = new ProfileScreen();
        QuizSelectionScreen QuizScreen = new QuizSelectionScreen(profileScreen, Listener);
        QuizScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_QuizSelectionButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
         SettingsScreen Settings = new SettingsScreen();
        Settings.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        // TODO add your handling code here:
        ProfileScreen Profile = new ProfileScreen();
        Profile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
        // TODO add your handling code here:
        HelpScreen Help = new HelpScreen();
        Help.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void LeaderboardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaderboardsButtonActionPerformed
        // TODO add your handling code here:
        LeaderboardScreen Leaderboard = new LeaderboardScreen();
        Leaderboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LeaderboardsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppIcon;
    private javax.swing.JPanel GreenBackground;
    private javax.swing.JButton HelpButton;
    private javax.swing.JLabel HomePageHeading;
    private javax.swing.JButton LeaderboardsButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton QuizSelectionButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
