/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIScreens_package;

import GUIScreensCode.FrameUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author alexv
 */
public class LeaderboardBODMAS extends javax.swing.JFrame {

    /**
     * Creates new form LeaderboardBODMAS
     */
    public LeaderboardBODMAS() {
        initComponents();
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();
        
        Top100Easy.setEditable(false);
        Top100Medium.setEditable(false);
        Top100Hard.setEditable(false);

    }

    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        GreenBackground = new javax.swing.JPanel();
        BodmasLeaderHeading = new javax.swing.JLabel();
        EasyHeading = new javax.swing.JLabel();
        MediumHeading = new javax.swing.JLabel();
        HardHeading = new javax.swing.JLabel();
        Top100Easy = new javax.swing.JTextField();
        Top100Hard = new javax.swing.JTextField();
        Top100Medium = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        BODMASLeaderImage = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GreenBackground.setBackground(new java.awt.Color(0, 102, 0));

        BodmasLeaderHeading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BodmasLeaderHeading.setText("BODMAS Leaderboard");

        EasyHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EasyHeading.setForeground(new java.awt.Color(255, 102, 0));
        EasyHeading.setText("Easy:");

        MediumHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MediumHeading.setForeground(new java.awt.Color(255, 102, 0));
        MediumHeading.setText("Medium:");

        HardHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HardHeading.setForeground(new java.awt.Color(255, 102, 0));
        HardHeading.setText("Hard:");

        BackButton.setBackground(new java.awt.Color(255, 102, 0));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        BODMASLeaderImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BodmasImageLeaderboard.png"))); // NOI18N

        javax.swing.GroupLayout GreenBackgroundLayout = new javax.swing.GroupLayout(GreenBackground);
        GreenBackground.setLayout(GreenBackgroundLayout);
        GreenBackgroundLayout.setHorizontalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(EasyHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(MediumHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HardHeading)
                        .addGap(94, 94, 94))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addComponent(Top100Medium, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BODMASLeaderImage)
                            .addComponent(Top100Hard, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Top100Easy, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BodmasLeaderHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GreenBackgroundLayout.setVerticalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BodmasLeaderHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GreenBackgroundLayout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(BODMASLeaderImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addComponent(HardHeading)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GreenBackgroundLayout.createSequentialGroup()
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EasyHeading)
                            .addComponent(MediumHeading))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Top100Easy, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Top100Medium, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Top100Hard, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        LeaderboardScreen Leaderboard = new LeaderboardScreen();
        Leaderboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardBODMAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardBODMAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardBODMAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardBODMAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LeaderboardBODMAS().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BODMASLeaderImage;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BodmasLeaderHeading;
    private javax.swing.JLabel EasyHeading;
    private javax.swing.JPanel GreenBackground;
    private javax.swing.JLabel HardHeading;
    private javax.swing.JLabel MediumHeading;
    private javax.swing.JTextField Top100Easy;
    private javax.swing.JTextField Top100Hard;
    private javax.swing.JTextField Top100Medium;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
