/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIScreens_package;

import GUIScreensCode.FrameUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author alexv
 */
public class LeaderboardTimesTables extends javax.swing.JFrame {

    private ArrayList<Integer> timesEasy = new ArrayList<>();
    private ArrayList<Integer> timesMedium = new ArrayList<>();
    private ArrayList<Integer> timesHard = new ArrayList<>();

    /**
     * Creates new form LeaderboardTimesTables
     */
    public LeaderboardTimesTables() {
        initComponents();
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();
        initializeTimes();
        //updateLeaderboard(timeRemaining, quizDifficulty);

        // Set Top100Easy JTextArea as read-only
        Top100Easy.setEditable(false);

        // Set Top100Medium JTextArea as read-only
        Top100Medium.setEditable(false);

        // Set Top100Hard JTextArea as read-only
        Top100Hard.setEditable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        // Adjusting scroll pane for Top100Medium JTextArea
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        // Adjusting scroll pane for Top100Hard JTextArea
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    /**
     * Initialize times with dummy data for demonstration.
     */
    private void initializeTimes() {
        // Dummy data initialization (replace with actual time recording logic)
        timesEasy.add(50);
        timesEasy.add(45);
        timesEasy.add(48);
        timesMedium.add(60);
        timesMedium.add(55);
        timesMedium.add(58);
        timesHard.add(75);
        timesHard.add(70);
        timesHard.add(72);
    }

    public ArrayList<Integer> getTimesEasy() {
        return timesEasy;
    }

    public ArrayList<Integer> getTimesMedium() {
        return timesMedium;
    }

    public ArrayList<Integer> getTimesHard() {
        return timesHard;
    }

    /**
     * Update the Leader board display.
     */
    public void updateLeaderboard(int timeRemaining, String quizDifficulty) {
        Collections.sort(timesEasy);
        Collections.sort(timesMedium);
        Collections.sort(timesHard);

        // Display top 50 times for Easy difficulty
        StringBuilder easyTimes = new StringBuilder();
        for (int i = 0; i < Math.min(50, timesEasy.size()); i++) {
            easyTimes.append(timesEasy.get(i)).append("\n");
        }
        SwingUtilities.invokeLater(() -> {
            Top100Easy.setText(easyTimes.toString());
        });

        // Display top 50 times for Medium difficulty
        StringBuilder mediumTimes = new StringBuilder();
        for (int i = 0; i < Math.min(50, timesMedium.size()); i++) {
            mediumTimes.append(timesMedium.get(i)).append("\n");
        }
        SwingUtilities.invokeLater(() -> {
            Top100Medium.setText(mediumTimes.toString());
        });

        // Display top 50 times for Hard difficulty
        StringBuilder hardTimes = new StringBuilder();
        for (int i = 0; i < Math.min(50, timesHard.size()); i++) {
            hardTimes.append(timesHard.get(i)).append("\n");
        }
        SwingUtilities.invokeLater(() -> {
            Top100Hard.setText(hardTimes.toString());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GreenBackground = new javax.swing.JPanel();
        LeaderboardHeading = new javax.swing.JLabel();
        EasyHeading = new javax.swing.JLabel();
        MediumHeading = new javax.swing.JLabel();
        HardHeading = new javax.swing.JLabel();
        TimesTablesLeaderboardImage = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Top100Easy = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Top100Medium = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Top100Hard = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GreenBackground.setBackground(new java.awt.Color(0, 102, 0));

        LeaderboardHeading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LeaderboardHeading.setText("Times Tables Leaderboard");

        EasyHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EasyHeading.setForeground(new java.awt.Color(255, 102, 0));
        EasyHeading.setText("Easy:");

        MediumHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MediumHeading.setForeground(new java.awt.Color(255, 102, 0));
        MediumHeading.setText("Medium:");

        HardHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HardHeading.setForeground(new java.awt.Color(255, 102, 0));
        HardHeading.setText("Hard:");

        TimesTablesLeaderboardImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/TimesTableImageLeaderBoard.jpg"))); // NOI18N

        BackButton.setBackground(new java.awt.Color(255, 102, 0));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Top100Easy.setColumns(20);
        Top100Easy.setRows(5);
        jScrollPane1.setViewportView(Top100Easy);

        Top100Medium.setColumns(20);
        Top100Medium.setRows(5);
        jScrollPane2.setViewportView(Top100Medium);

        Top100Hard.setColumns(20);
        Top100Hard.setRows(5);
        jScrollPane3.setViewportView(Top100Hard);

        javax.swing.GroupLayout GreenBackgroundLayout = new javax.swing.GroupLayout(GreenBackground);
        GreenBackground.setLayout(GreenBackgroundLayout);
        GreenBackgroundLayout.setHorizontalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(EasyHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(MediumHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HardHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LeaderboardHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TimesTablesLeaderboardImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GreenBackgroundLayout.setVerticalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimesTablesLeaderboardImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LeaderboardHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HardHeading)
                            .addComponent(MediumHeading))
                        .addGap(24, 24, 24)
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addGap(105, 105, 105))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addComponent(EasyHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        LeaderboardScreen Leaderboard = new LeaderboardScreen();
        Leaderboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardTimesTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LeaderboardTimesTables().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel EasyHeading;
    private javax.swing.JPanel GreenBackground;
    private javax.swing.JLabel HardHeading;
    private javax.swing.JLabel LeaderboardHeading;
    private javax.swing.JLabel MediumHeading;
    private javax.swing.JLabel TimesTablesLeaderboardImage;
    private javax.swing.JTextArea Top100Easy;
    private javax.swing.JTextArea Top100Hard;
    private javax.swing.JTextArea Top100Medium;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
