/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIScreens_package;

import GUIScreensCode.FrameUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author alexv
 */
public class LeaderboardScreen extends javax.swing.JFrame {

    /**
     * Creates new form LeaderboardScreen
     */
    public LeaderboardScreen() {
        initComponents();
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();
        ToolTip.setToolTipText("Welcome to the leaberboard, achieve higher scores and better times to reach the top!");
    }

    /**
     * Apply the saved background color to the container of this frame.
     */
    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

    /**
     * Recursively change the background color of all panels within a container.
     * @param container The container whose components backgrounds are to be changed.
     * @param color The color to set as the background.
     */
    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GreenBackground = new javax.swing.JPanel();
        WelcomeToLeaderboardJlabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        AlgebraLeaderButton = new javax.swing.JButton();
        TimesTableLeaderButton = new javax.swing.JButton();
        BODMASLeaderButton = new javax.swing.JButton();
        LeaderboardIcon = new javax.swing.JLabel();
        ToolTip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GreenBackground.setBackground(new java.awt.Color(0, 102, 0));

        WelcomeToLeaderboardJlabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        WelcomeToLeaderboardJlabel.setText("Welcome to the Leaderboards!");

        BackButton.setBackground(new java.awt.Color(255, 102, 0));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        AlgebraLeaderButton.setBackground(new java.awt.Color(255, 102, 0));
        AlgebraLeaderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AlgebraLeaderButton.setText("Algebra Leaderboard");
        AlgebraLeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgebraLeaderButtonActionPerformed(evt);
            }
        });

        TimesTableLeaderButton.setBackground(new java.awt.Color(255, 102, 0));
        TimesTableLeaderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TimesTableLeaderButton.setText("Times Tables (1 to 12) Leaderboard");
        TimesTableLeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimesTableLeaderButtonActionPerformed(evt);
            }
        });

        BODMASLeaderButton.setBackground(new java.awt.Color(255, 102, 0));
        BODMASLeaderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BODMASLeaderButton.setText("BODMAS Leaderboard");
        BODMASLeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BODMASLeaderButtonActionPerformed(evt);
            }
        });

        LeaderboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LeaderboardIconEditted.png"))); // NOI18N

        ToolTip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ToolTipIcon.png"))); // NOI18N
        ToolTip.setToolTipText("Choose a quiz category to begin. Each category offers different challenges!\n");

        javax.swing.GroupLayout GreenBackgroundLayout = new javax.swing.GroupLayout(GreenBackground);
        GreenBackground.setLayout(GreenBackgroundLayout);
        GreenBackgroundLayout.setHorizontalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BODMASLeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlgebraLeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimesTableLeaderButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(LeaderboardIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(WelcomeToLeaderboardJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GreenBackgroundLayout.setVerticalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(WelcomeToLeaderboardJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TimesTableLeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AlgebraLeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LeaderboardIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(BODMASLeaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TimesTableLeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimesTableLeaderButtonActionPerformed
        // TODO add your handling code here:
        LeaderboardTimesTables TimesTables = new LeaderboardTimesTables();
        TimesTables.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TimesTableLeaderButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        HomeScreen HomeButton = new HomeScreen();
        HomeButton.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AlgebraLeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgebraLeaderButtonActionPerformed
        // TODO add your handling code here:
        LeaderboardAlgebra Algebra = new LeaderboardAlgebra();
        Algebra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AlgebraLeaderButtonActionPerformed

    private void BODMASLeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BODMASLeaderButtonActionPerformed
        // TODO add your handling code here:
        LeaderboardBODMAS BODMAS = new LeaderboardBODMAS();
        BODMAS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BODMASLeaderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LeaderboardScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlgebraLeaderButton;
    private javax.swing.JButton BODMASLeaderButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel GreenBackground;
    private javax.swing.JLabel LeaderboardIcon;
    private javax.swing.JButton TimesTableLeaderButton;
    private javax.swing.JLabel ToolTip;
    private javax.swing.JLabel WelcomeToLeaderboardJlabel;
    // End of variables declaration//GEN-END:variables
}
