/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIScreens_package;

import GUIScreensCode.FrameUtils;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author alexv
 */
public class LeaderboardAlgebra extends javax.swing.JFrame {

    /**
     * Creates new form LeaderboardAlgebra
     */
    public LeaderboardAlgebra() {
        initComponents();
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();

        Top100Easy.setEditable(false);

        Top100Medium.setEditable(false);

        Top100Hard.setEditable(false);
    }

    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JPanel();
        AlgebraLeaderHeading = new javax.swing.JLabel();
        EasyHeading = new javax.swing.JLabel();
        MediumHeading = new javax.swing.JLabel();
        HardHeading = new javax.swing.JLabel();
        Top100Easy = new javax.swing.JTextField();
        Top100Medium = new javax.swing.JTextField();
        AlgebraLeaderboardImage = new javax.swing.JLabel();
        BackButtonPress = new javax.swing.JButton();
        Top100Hard = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackButton.setBackground(new java.awt.Color(0, 102, 0));

        AlgebraLeaderHeading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        AlgebraLeaderHeading.setText("Algebra Leaderboard");

        EasyHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EasyHeading.setForeground(new java.awt.Color(255, 102, 0));
        EasyHeading.setText("Easy:");

        MediumHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MediumHeading.setForeground(new java.awt.Color(255, 102, 0));
        MediumHeading.setText("Medium:");

        HardHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HardHeading.setForeground(new java.awt.Color(255, 102, 0));
        HardHeading.setText("Hard:");

        Top100Easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Top100EasyActionPerformed(evt);
            }
        });

        AlgebraLeaderboardImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AlgebraImageLeaderboard.png"))); // NOI18N

        BackButtonPress.setBackground(new java.awt.Color(255, 102, 0));
        BackButtonPress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButtonPress.setText("Back");
        BackButtonPress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonPressActionPerformed(evt);
            }
        });

        Top100Hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Top100HardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackButtonLayout = new javax.swing.GroupLayout(BackButton);
        BackButton.setLayout(BackButtonLayout);
        BackButtonLayout.setHorizontalGroup(
            BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackButtonLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(AlgebraLeaderHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlgebraLeaderboardImage)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BackButtonLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EasyHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Top100Easy, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackButtonLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(MediumHeading))
                    .addGroup(BackButtonLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Top100Medium, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackButtonLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Top100Hard, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackButtonLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(HardHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))))
            .addGroup(BackButtonLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BackButtonPress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackButtonLayout.setVerticalGroup(
            BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AlgebraLeaderHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlgebraLeaderboardImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HardHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MediumHeading)
                    .addComponent(EasyHeading))
                .addGap(2, 2, 2)
                .addGroup(BackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Top100Medium, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Top100Easy, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Top100Hard, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(BackButtonPress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Top100EasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Top100EasyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Top100EasyActionPerformed

    private void Top100HardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Top100HardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Top100HardActionPerformed

    private void BackButtonPressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonPressActionPerformed
        LeaderboardScreen Leaderboard = new LeaderboardScreen();
        Leaderboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonPressActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardAlgebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardAlgebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardAlgebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LeaderboardAlgebra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LeaderboardAlgebra().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlgebraLeaderHeading;
    private javax.swing.JLabel AlgebraLeaderboardImage;
    private javax.swing.JPanel BackButton;
    private javax.swing.JButton BackButtonPress;
    private javax.swing.JLabel EasyHeading;
    private javax.swing.JLabel HardHeading;
    private javax.swing.JLabel MediumHeading;
    private javax.swing.JTextField Top100Easy;
    private javax.swing.JTextField Top100Hard;
    private javax.swing.JTextField Top100Medium;
    // End of variables declaration//GEN-END:variables
}
