package GUIScreens_package;

import GUIScreensCode.AlgebraQuizListener;
import GUIScreensCode.Difficulty;
import GUIScreensCode.FrameUtils;
import GUIScreensCode.QuizType;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.util.prefs.Preferences;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import GUIScreens_package.QuizSelectionScreen;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;

/**
 *
 * @author Alex von Allemann 12-5/K1 QuizSelectionScreenGUI
 */
public class QuizSelectionScreen extends javax.swing.JFrame {

    private AlgebraQuizListener algebraQuizListener;
    private Preferences prefs;
    private ProfileScreen profileScreen;

    public QuizSelectionScreen(ProfileScreen profileScreen, AlgebraQuizListener listener) {
        this.profileScreen = profileScreen;
        this.algebraQuizListener = listener;
        initComponents();
        getContentPane().setBackground(Color.green); //Green background.
        Color col = new Color(0, 102, 0);
        getContentPane().setBackground(col); //Set background color to green.
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();
        ToolTip.setToolTipText("Choose a quiz category to begin. Each category offers different challenges!");
        prefs = Preferences.userNodeForPackage(GUIScreens_package.QuizSelectionScreen.class);

        // Initially set Algebra button visibility based on stored preference
        boolean algebraBadgeVisible = prefs.getBoolean("algebraBadgeVisible", false);
        Algebra.setVisible(algebraBadgeVisible);
        Algebra.setVisible(true);

    }

    // public void setAlgebraQuizListener(AlgebraQuizListener listener) {
    //     this.listener = listener;
    //}
    //Method to select the Algebra Quiz
    public void selectAlgebraQuiz() {
        // Perform selection logic
        if (algebraQuizListener != null) {
            algebraQuizListener.onAlgebraQuizSelected(); // Notify listener
        }
    }

    private void algebraButtonPressed() {
        if (algebraQuizListener != null) {
            algebraQuizListener.onAlgebraQuizSelected();
        }
    }

    /**
     * Method to apply the saved background color preference to the container.
     */
    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

    /**
     * Method to change background color of a container and its components
     * recursively.
     *
     * @param container The container to change background color for.
     * @param color The new background color.
     */
    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    public interface AlgebraQuizListener {

        void onAlgebraQuizSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GreenBackground = new javax.swing.JPanel();
        ChooseQuizHeading = new javax.swing.JLabel();
        TimesTables = new javax.swing.JButton();
        Bodmas = new javax.swing.JButton();
        Algebra = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        RedArrow3 = new javax.swing.JLabel();
        RedArrow1 = new javax.swing.JLabel();
        RedArrow2 = new javax.swing.JLabel();
        ToolTip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GreenBackground.setBackground(new java.awt.Color(0, 102, 0));

        ChooseQuizHeading.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        ChooseQuizHeading.setText("Choose your Quiz!");

        TimesTables.setBackground(new java.awt.Color(255, 102, 0));
        TimesTables.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TimesTables.setText("Times tables (1 to 12)");
        TimesTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimesTablesActionPerformed(evt);
            }
        });

        Bodmas.setBackground(new java.awt.Color(255, 102, 0));
        Bodmas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bodmas.setText("BODMAS");
        Bodmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodmasActionPerformed(evt);
            }
        });

        Algebra.setBackground(new java.awt.Color(255, 102, 0));
        Algebra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Algebra.setText("Algebra");
        Algebra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgebraActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(255, 102, 0));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setText("Back ");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        RedArrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/RedArrowDownNew.png"))); // NOI18N

        RedArrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/RedArrowDownNew.png"))); // NOI18N

        RedArrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/RedArrowDownNew.png"))); // NOI18N

        ToolTip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ToolTipIcon.png"))); // NOI18N
        ToolTip.setToolTipText("Choose a quiz category to begin. Each category offers different challenges!\n");

        javax.swing.GroupLayout GreenBackgroundLayout = new javax.swing.GroupLayout(GreenBackground);
        GreenBackground.setLayout(GreenBackgroundLayout);
        GreenBackgroundLayout.setHorizontalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(TimesTables, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Bodmas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Algebra, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GreenBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addComponent(ToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChooseQuizHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GreenBackgroundLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(RedArrow1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(RedArrow2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RedArrow3)
                .addGap(51, 51, 51))
        );
        GreenBackgroundLayout.setVerticalGroup(
            GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChooseQuizHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RedArrow1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GreenBackgroundLayout.createSequentialGroup()
                        .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(RedArrow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(GreenBackgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RedArrow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(GreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimesTables, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bodmas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Algebra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GreenBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TimesTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimesTablesActionPerformed
        // TODO add your handling code here:
        // profileScreen.setTimesTablesBadgeVisible(true);
        DifficultySelectionTimesTables DifTimeTables = new DifficultySelectionTimesTables();
        DifTimeTables.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_TimesTablesActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        HomeScreen HomeButton = new HomeScreen();
        HomeButton.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BodmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodmasActionPerformed
        //  profileScreen.setBodmasBadgeVisible(true);
        DifficultySelectionBodmas DifBodmas = new DifficultySelectionBodmas();
        DifBodmas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BodmasActionPerformed

    private void AlgebraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgebraActionPerformed
        algebraButtonPressed();
        // Save the state
        Preferences prefs = Preferences.userNodeForPackage(ProfileScreen.class);
        // profileScreen.setAlgebraBadgeVisible(true);
        prefs.putBoolean("algebraBadgeVisible", true);
        // profileScreen.setAlgebraBadgeVisible(true);
        // profileScreen.setAlgebraBadgeVisible(true);
        DifficultySelectionAlgebra DifAlgebra = new DifficultySelectionAlgebra();
        DifAlgebra.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AlgebraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfileScreen profileScreen = new ProfileScreen();
                AlgebraQuizListener listener = new AlgebraQuizListener() {
                    @Override
                    public void onAlgebraQuizSelected() {
                        // Implement the logic to be executed when the Algebra quiz is selected
                    }
                };
                QuizSelectionScreen quizScreen = new QuizSelectionScreen(profileScreen, listener);
                quizScreen.setVisible(true);
                // new QuizSelectionScreen()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Algebra;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Bodmas;
    private javax.swing.JLabel ChooseQuizHeading;
    private javax.swing.JPanel GreenBackground;
    private javax.swing.JLabel RedArrow1;
    private javax.swing.JLabel RedArrow2;
    private javax.swing.JLabel RedArrow3;
    private javax.swing.JButton TimesTables;
    private javax.swing.JLabel ToolTip;
    // End of variables declaration//GEN-END:variables
}
