/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIScreens_package;

import GUIScreensCode.AccountInformationData;
import GUIScreensCode.FrameUtils;
import GUIScreensCode.NotificationManagementPanel;
import GUIScreensCode.NotificationPreferences;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SD10009935 Alex von Allemann SettingsScreen
 */
public class SettingsScreen extends javax.swing.JFrame {

    private NotificationManagementPanel notificationPanel; //new Panel for notifications
    private JButton manageNotificationsButton; //Button to show notification management

    public SettingsScreen() {
        initComponents(); // Call initComponents in the Constructor
        updateNameLabel();
        updateNameLabel1();
        notificationPanel = new NotificationManagementPanel();
        getContentPane().setBackground(FrameUtils.getBackgroundColor());
        FrameUtils.addFrame(this);
        applySavedBackgroundColor();
    }
    //apply the saved background color
    private void applySavedBackgroundColor() {
        Color savedColor = FrameUtils.getBackgroundColor();
        changeContainerBackground(this.getContentPane(), savedColor);
    }

    //changes the containers background color
    public static void changeContainerBackground(Container container, Color color) {
        for (Component component : container.getComponents()) {
            if (component instanceof JPanel) {
                component.setBackground(color);
            }
            if (component instanceof Container) {
                changeContainerBackground((Container) component, color);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SettingsHeading = new javax.swing.JLabel();
        ThemesButton = new javax.swing.JButton();
        NotificationButton = new javax.swing.JButton();
        SettingsIcon = new javax.swing.JLabel();
        AccountInformation = new javax.swing.JLabel();
        Nametext = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        AppVersion = new javax.swing.JLabel();
        SaveButton1 = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        SaveButton2 = new javax.swing.JButton();
        NameLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        SettingsHeading.setBackground(new java.awt.Color(255, 102, 0));
        SettingsHeading.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        SettingsHeading.setText("Settings");

        ThemesButton.setBackground(new java.awt.Color(255, 102, 0));
        ThemesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ThemesButton.setText("Themes");
        ThemesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemesButtonActionPerformed(evt);
            }
        });

        NotificationButton.setBackground(new java.awt.Color(255, 102, 0));
        NotificationButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NotificationButton.setText("Notification Preferences");
        NotificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationButtonActionPerformed(evt);
            }
        });

        SettingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SettingsImage.png"))); // NOI18N

        AccountInformation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccountInformation.setText("Account Information:");

        Nametext.setText("Name/Alias: ");

        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        EmailLabel.setText("Email:");

        BackButton.setBackground(new java.awt.Color(255, 102, 0));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        AppVersion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        AppVersion.setText("App Version: 1.54");

        SaveButton1.setBackground(new java.awt.Color(255, 102, 0));
        SaveButton1.setText("SAVE");
        SaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton1ActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        SaveButton2.setBackground(new java.awt.Color(255, 102, 0));
        SaveButton2.setText("SAVE");
        SaveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton2ActionPerformed(evt);
            }
        });

        NameLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AccountInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(SettingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(ThemesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NotificationButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nametext)
                                            .addComponent(EmailLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(EmailTextField))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SaveButton2)
                                            .addComponent(SaveButton1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SettingsHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SettingsHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SettingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ThemesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NotificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccountInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nametext)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SaveButton1)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmailLabel)
                        .addComponent(SaveButton2)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        HomeScreen HomeButton = new HomeScreen();
        HomeButton.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ThemesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemesButtonActionPerformed
        // TODO add your handling code here:
        ThemePage Themes = new ThemePage();
        Themes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ThemesButtonActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void SaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton1ActionPerformed
        // TODO add your handling code here:
        String text = NameTextField.getText();
        AccountInformationData.getInstance().setName(text); // Save the name to the data model
        updateNameLabel(); //Update the display with the saved name
        saveToFile(text); //Save the name/alias to a file 
        saveText(text);

    }//GEN-LAST:event_SaveButton1ActionPerformed

    private void SaveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton2ActionPerformed
        // TODO add your handling code here:
        String text1 = EmailTextField.getText();
        AccountInformationData.getInstance().setEmail(text1); // Save the email to the data model
        updateNameLabel1(); //Update the display with the saved email
        saveToFile1(text1); // Save to file
        saveText(text1);

    }//GEN-LAST:event_SaveButton2ActionPerformed
   //Method to show the notification panel 
    private void showNotificationManagementPanel() {
        if (notificationPanel != null) {
            // Set initial values from existing preferences (optional)
            NotificationPreferences preferences = new NotificationPreferences();
            notificationPanel.setInitialValues(preferences);

            // Create a dialog to show the panel
            JDialog dialog = new JDialog(this, "Notification Preferences", true); // true for modal
            dialog.setLayout(new BorderLayout());

            dialog.add(notificationPanel, BorderLayout.CENTER);

            JButton closeButton = new JButton("Close");
            closeButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialog.setVisible(false);
                    dialog.dispose(); // Close the dialog when the button is clicked

                    jPanel1.remove(notificationPanel);
                    jPanel1.validate();
                    jPanel1.repaint();

                    getContentPane().remove(notificationPanel);
                    validate();
                    repaint();
                }
            });
            dialog.add(closeButton, BorderLayout.SOUTH);
            // Sets the dialog properties
            //Sets the size of the dialog box
            dialog.setSize(300, 200);
            dialog.setLocationRelativeTo(this); // Center dialog relative to the SettingsScreen
            dialog.setVisible(true); // Show the dialog
        } else {
            System.out.println("Notification panel is not initialized correctly");
        }
    }
    private void NotificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationButtonActionPerformed
        // TODO add your handling code here:
        showNotificationManagementPanel();


    }//GEN-LAST:event_NotificationButtonActionPerformed

    
    private void updateNameLabel() {
        String name = AccountInformationData.getInstance().getName();
        NameLabel.setText(name); // Update the label with the saved name
    }

    private void updateNameLabel1() {
        String email = AccountInformationData.getInstance().getEmail();
        NameLabel1.setText(email); //update the label with the saved email
    }

    //Save preferences to a file
    private void saveToFile(String text) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("savedName.txt"))) {
            writer.write(text);
            JOptionPane.showMessageDialog(this, "Your name/alias was saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving name: " + e.getMessage());
        }
    }

    private void saveToFile1(String text1) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("savedEmail.txt"))) {
            writer.write(text1);
            JOptionPane.showMessageDialog(this, "Your Email was saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving Email: " + e.getMessage());
        }
    }

    //method to save text
    private void saveText(String text) {
        //System.out.println("Name saved: " + text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsScreen().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountInformation;
    private javax.swing.JLabel AppVersion;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel Nametext;
    private javax.swing.JButton NotificationButton;
    private javax.swing.JButton SaveButton1;
    private javax.swing.JButton SaveButton2;
    private javax.swing.JLabel SettingsHeading;
    private javax.swing.JLabel SettingsIcon;
    private javax.swing.JButton ThemesButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
